/**
 * Static interface text, HR/EN.
 *
 * This is for the site's own chrome — navigation, buttons, headings, empty
 * states. Editable *content* does not belong here: that lives in WordPress and
 * is read through `localized()` in ./i18n.
 *
 * Croatian is the source of truth. A missing English entry falls back to
 * Croatian rather than showing a key, so a half-finished translation degrades
 * into a mixed page instead of a broken one — the same rule content follows.
 *
 *   const t = useUI();
 *   <button>{t("common.readMore")}</button>
 */

import { useRouter } from "next/router";
import { isEnglish } from "./i18n";

/** Croatian is the complete set; English may lag behind it. */
export const HR = {
  // ---- navigation ----------------------------------------------------
  "nav.main": "Glavna navigacija",
  "nav.home": "Početna",
  "nav.obavijesti": "Obavijesti",
  "nav.studentServis": "Student servis",
  "nav.poslovi": "Poslovi",
  "nav.prehrana": "Prehrana",
  "nav.smjestaj": "Smještaj",
  "nav.sport": "Sport",
  "nav.kultura": "Kultura",
  "nav.turizam": "Turizam",
  "nav.catering": "Catering",
  "nav.najamProstora": "Najam prostora",
  "nav.mediji": "Mediji",
  "nav.teatarTd": "Teatar &TD",
  "nav.francuskiPaviljon": "Francuski paviljon",
  "nav.prijava": "Prijava",
  "nav.prijavaStudent": "Prijava student",
  "nav.prijavaPoslodavac": "Prijava poslodavac",
  "nav.zaposlenici": "Zaposlenici",
  "nav.accessibility": "Pristupačnost",

  // ---- common UI -----------------------------------------------------
  "common.readMore": "Saznaj više",
  "common.faq": "Često postavljana pitanja",
  "common.questionsAndHelp": "Pitanja i pomoć",
  "common.contact": "Kontakt",
  "common.workingHours": "Radno vrijeme blagajni",
  "common.location": "Lokacija",
  "common.relatedContent": "Popratni sadržaj",
  "common.documents": "Dokumenti",
  "common.gallery": "Galerija",

  // ---- empty states --------------------------------------------------
  "empty.obavijesti": "Nema obavijesti za prikaz",
  "empty.faq": "Nema pitanja za prikaz",
  "empty.notFound": "Nije pronađena obavijest",

  // ---- organisation --------------------------------------------------
  "org.name": "Studentski centar u Zagrebu",
  "org.university": "Sveučilište u Zagrebu",

  "smjestaj.pageTitle": "Smještaj",
  "smjestaj.dorms": "Studentski domovi",
  "smjestaj.dormsUpper": "STUDENTSKI DOMOVI",
  "smjestaj.stay": "Boravak u studentskome domu",
  "smjestaj.criteria":
    "Poštovani budući stanari studentskih domova, za boravak u studentskome domu potrebno je ispuniti slijedeći kriteriji:",
  "smjestaj.applyTender": "Prijava za natječaj",
  "smjestaj.applyVia":
    "Za prijavu na natječaj za studentski smještaj prijavite se putem linka  nastavku.",
  "smjestaj.counselling": "SAVJETOVALIŠTE",
  "smjestaj.intro":
    "SC Zagreb nudi smještaj u 4 studentska doma na atraktivnim lokacijama u gradu Zagrebu.",
  "smjestaj.newsTitle": "Obavijesti - studentski smještaj",
  "cards.contact": "Kontakt",
  "cards.settlements": "Naselja",
  "cards.tender": "Natječaj",
  "cards.prehranaUpper": "PREHRANA",
  "cards.smjestajUpper": "SMJEŠTAJ",
  "cards.studentServisUpper": "STUDENT SERVIS",
  "cards.jobs": "Poslovi",
  "cards.becomeMember": "Postani član",
  "cards.signIn": "Prijava",
  "cards.restaurants": "Restorani",
  "kultura.pageTitle": "Kultura",
  "kultura.today": "Danas",
  "kultura.goToList": "Idi na popis",
  "kultura.eventCalendar": "Kalendar evenata",
  "kultura.noEventsToday": "Nema evenata na današnji dan",
  "kultura.coursesWorkshops": "Tečajevi i radionice",
  "common.readMoreUpper": "SAZNAJ VIŠE",
  "sport.yearRound": "CJELOGODIŠNJE",
  "sport.educational": "EDUKACIJSKE AKTIVNOSTI",
  "sport.information": "INFORMACIJE",
  "sport.competitive": "NATJECATELJSKE AKTIVNOSTI",
  "sport.occasional": "POVREMENE",
  "sport.recreational": "REKREACIJSKE AKTIVNOSTI",
  "sport.photos": "SLIKE",
  "sport.sporting": "SPORTSKE",
  "sport.professional": "STRUČNE",
  "sport.social": "ZABAVNE AKTIVNOSTI",
  "prehrana.dailyMenu": "Dnevni meni",
  "prehrana.breakfast": "Doručak",
  "prehrana.lunch": "Ručak",
  "prehrana.dinner": "Večera",
  "prehrana.choice": "Izbor",
  "prehrana.sides": "Prilozi",
  "prehrana.menu": "Menu",
  "prehrana.vegetarian": "Vegeterijanski menu",
  "empty.menus": "Nema menija za prikaz",
  "home.information": "Informacije",
  "home.calendar": "Kalendar",

  "a11y.title": "Pristupačnost",
  "a11y.clear": "Obriši odabir",
  "a11y.underlineLinks": "Podcrtaj poveznice",
  "a11y.largeText": "Povećani tekst",
  "a11y.grayscale": "Sivi tonovi",
  "a11y.lightBackground": "Svijetla pozadina",
  "a11y.highContrast": "Visoki kontrast",
  "a11y.readableFont": "Čitljiv font",
  "membership.title": "Članstvo u student servisu",
  "membership.photos": "Dvije male fotografije",
  "membership.idCard": "Osobna iskaznica",
  "membership.bankAccount": "Osobni žiro ili tekući račun u banci na teritoriju Republike Hrvatske",
  "membership.diploma": "Preslika svjedodžbe završnog razreda srednje škole ili maturalne svjedodžbe",
  "membership.status": "Status studenta/ice za tekuću akademsku godinu",
  "membership.xica": "Studentska iskaznica - X-ica",
  "membership.employers": "Članstvo poslodavaca u Student servis",
  "membership.employersIntro": "Jednostavan sustav prijave ovih poslodavaca u bazu Studentskog centra u Zagrebu.",
  "sport.pageTitle": "Sport",
  "sport.pageTitleUpper": "SPORT",
  "sport.educationalTc": "Edukacijske aktivnosti",
  "sport.competitiveTc": "Natjecateljske aktivnosti",
  "sport.recreationalTc": "Rekreacijske aktivnosti",
  "sport.fun": "Zabava",
  "prehrana.pageTitle": "Prehrana",
  "prehrana.restaurants": "Restorani",
  "prehrana.restaurantsTitle": "Restorani Studentskog Centra u Zagrebu",
  "prehrana.studentLogin": "Student - prijava u issp.srce.hr",
  "jobs.pageTitle": "Svi poslovi",
  "jobs.forms": "Obrasci",
  "jobs.search": "Pretraži poslove...",
  "jobs.type": "Vrsta posla",
  "jobs.searchUpper": "PRETRAŽI POSLOVE",
  "jobs.metaTitle": "Ponuda poslova; Studentski centar u Zagrebu; Sveučilište u Zagrebu",
  "empty.jobs": "Nema poslova za prikaz",
  "ss.pageTitle": "Student servis",
  "ss.signupMembershipEmployers": "PRIJAVA ČLANSTVO POSLODAVCI",
  "obavijesti.pageTitle": "Obavijesti",
  "obavijesti.all": "Sve obavijesti",
  "obavijesti.categories": "Kategorije",
  "obavijesti.search": "Pretraži obavijesti...",
  "obavijesti.metaTitle": "Obavijesti Studentskog Centra u Zagrebu",
  "dorm.photos": "Fotografije",
  "dorm.notFound": "Nije pronađen studentski dom",
  "empty.photos": "Nema fotografija za prikaz",

  "nutrition.importance": "Važnost kvalitetne prehrane",
  "nutrition.varied": "Raznovrsna prehrana",
  "nutrition.vitamins": "Vitamini i minerali",
  "nutrition.activity": "Tjelesna aktivnost",
  "nutrition.weight": "Normalna tjelesna masa",
  "sign.title": "Digitalno potpisivanje",
  "sign.contracts": "Digitalno potpisivanje ugovora",
  "sign.extract": "Izvadite ugovor za poslodavca preko baze podataka aktivnih poslodavaca Studentskog centra u Zagrebu.",
  "sign.mobile": "Potpišite ugovore digitalno putem mobitela kroz sigurnosni certifikat 4. razine. Brzo, jednostavno i sigurno.",
  "sign.sync": "Sinkronizacija sa bazom podataka",
  "help.address": "ADRESA",
  "help.email": "EMAIL ADRESA",
  "help.phone": "TELEFON",
  "help.directorsOffice": "URED RAVNATELJA",
  "contract.number": "BROJ UGOVORA",
  "contract.payments": "ISPLATE NAKNADA",
  "contract.taxFree": "NEOPOREZIVI PRIMITAK",
  "contract.signAfterEmployer": "POTPIS UGOVORA NAKON POSLODAVCA",
  "login.employer": "POSLODAVAC",
  "login.student": "STUDENT",
  "login.employerSignIn": "PRIJAVA POSLODAVAC",
  "login.studentSignIn": "PRIJAVA STUDENT",
  "nav.goHome": "Idi na početnu stranicu",
  "nav.openMenu": "Otvori navigaciju",
  "ads.close": "Zatvori oglas",
  "rent.title": "Plaćanje stanarine on-line putem",
  "rent.accessProfile": "Pristupiti osobnom profilu putem linka:",
  "rent.afterLogin": "Nakon prijave u osobni profil, kliknuti na „",
  "rent.charges": "Naplata smještaja",
  "rent.selectWhat": "U srednjem dijelu ekrana potrebno je odabrati što se plaća, na način da se odabir potvrdi klikom na praznu kučicu.",
} as const;

export type UIKey = keyof typeof HR;

/** Only the keys that have been translated need to appear here. */
export const EN: Partial<Record<UIKey, string>> = {
  "nav.main": "Main navigation",
  "nav.home": "Home",
  "nav.obavijesti": "News",
  "nav.studentServis": "Student service",
  "nav.poslovi": "Jobs",
  "nav.prehrana": "Dining",
  "nav.smjestaj": "Accommodation",
  "nav.sport": "Sport",
  "nav.kultura": "Culture",
  "nav.turizam": "Tourism",
  "nav.catering": "Catering",
  "nav.najamProstora": "Venue hire",
  "nav.mediji": "Media",
  // Proper names stay as they are.
  "nav.teatarTd": "Teatar &TD",
  "nav.francuskiPaviljon": "Francuski paviljon",
  "nav.prijava": "Sign in",
  "nav.prijavaStudent": "Student sign-in",
  "nav.prijavaPoslodavac": "Employer sign-in",
  "nav.zaposlenici": "Staff",
  "nav.accessibility": "Accessibility",

  "common.readMore": "Read more",
  "common.faq": "Frequently asked questions",
  "common.questionsAndHelp": "Questions and help",
  "common.contact": "Contact",
  "common.workingHours": "Cashier opening hours",
  "common.location": "Location",
  "common.relatedContent": "Facilities",
  "common.documents": "Documents",
  "common.gallery": "Gallery",

  "empty.obavijesti": "No news to show",
  "empty.faq": "No questions to show",
  "empty.notFound": "Notice not found",

  "org.name": "Studentski centar u Zagrebu",
  "org.university": "University of Zagreb",

  "smjestaj.pageTitle": "Accommodation",
  "smjestaj.dorms": "Student halls",
  "smjestaj.dormsUpper": "STUDENT HALLS",
  "smjestaj.stay": "Living in a student hall",
  "smjestaj.criteria":
    "Dear future residents, the following criteria must be met in order to live in a student hall:",
  "smjestaj.applyTender": "Apply to the call",
  "smjestaj.applyVia":
    "To apply for student accommodation, use the link below.",
  "smjestaj.counselling": "COUNSELLING",
  "smjestaj.intro":
    "SC Zagreb offers accommodation in four student halls in attractive locations across Zagreb.",
  "smjestaj.newsTitle": "News — student accommodation",
  "cards.contact": "Contact",
  "cards.settlements": "Villages",
  "cards.tender": "Call for applications",
  "cards.prehranaUpper": "DINING",
  "cards.smjestajUpper": "ACCOMMODATION",
  "cards.studentServisUpper": "STUDENT SERVICE",
  "cards.jobs": "Jobs",
  "cards.becomeMember": "Become a member",
  "cards.signIn": "Sign in",
  "cards.restaurants": "Restaurants",
  "kultura.pageTitle": "Culture",
  "kultura.today": "Today",
  "kultura.goToList": "Go to the list",
  "kultura.eventCalendar": "Event calendar",
  "kultura.noEventsToday": "No events today",
  "kultura.coursesWorkshops": "Courses and workshops",
  "common.readMoreUpper": "READ MORE",
  "sport.yearRound": "YEAR-ROUND",
  "sport.educational": "EDUCATIONAL ACTIVITIES",
  "sport.information": "INFORMATION",
  "sport.competitive": "COMPETITIVE ACTIVITIES",
  "sport.occasional": "OCCASIONAL",
  "sport.recreational": "RECREATIONAL ACTIVITIES",
  "sport.photos": "PHOTOS",
  "sport.sporting": "SPORTING",
  "sport.professional": "PROFESSIONAL",
  "sport.social": "SOCIAL ACTIVITIES",
  "prehrana.dailyMenu": "Daily menu",
  "prehrana.breakfast": "Breakfast",
  "prehrana.lunch": "Lunch",
  "prehrana.dinner": "Dinner",
  "prehrana.choice": "Choice",
  "prehrana.sides": "Sides",
  "prehrana.menu": "Menu",
  "prehrana.vegetarian": "Vegetarian menu",
  "empty.menus": "No menus to show",
  "home.information": "Information",
  "home.calendar": "Calendar",

  "a11y.title": "Accessibility",
  "a11y.clear": "Clear selection",
  "a11y.underlineLinks": "Underline links",
  "a11y.largeText": "Larger text",
  "a11y.grayscale": "Greyscale",
  "a11y.lightBackground": "Light background",
  "a11y.highContrast": "High contrast",
  "a11y.readableFont": "Readable font",
  "membership.title": "Student service membership",
  "membership.photos": "Two small photographs",
  "membership.idCard": "Identity card",
  "membership.bankAccount": "A personal giro or current account with a bank in the Republic of Croatia",
  "membership.diploma": "A copy of your final-year secondary school certificate or school-leaving certificate",
  "membership.status": "Student status for the current academic year",
  "membership.xica": "Student card — X-ica",
  "membership.employers": "Employer membership of the Student service",
  "membership.employersIntro": "A simple way for employers to register in the Studentski centar Zagreb database.",
  "sport.pageTitle": "Sport",
  "sport.pageTitleUpper": "SPORT",
  "sport.educationalTc": "Educational activities",
  "sport.competitiveTc": "Competitive activities",
  "sport.recreationalTc": "Recreational activities",
  "sport.fun": "Entertainment",
  "prehrana.pageTitle": "Dining",
  "prehrana.restaurants": "Restaurants",
  "prehrana.restaurantsTitle": "Restaurants of Studentski centar Zagreb",
  "prehrana.studentLogin": "Students — sign in at issp.srce.hr",
  "jobs.pageTitle": "All jobs",
  "jobs.forms": "Forms",
  "jobs.search": "Search jobs…",
  "jobs.type": "Job type",
  "jobs.searchUpper": "SEARCH JOBS",
  "jobs.metaTitle": "Job listings; Studentski centar u Zagrebu; University of Zagreb",
  "empty.jobs": "No jobs to show",
  "ss.pageTitle": "Student service",
  "ss.signupMembershipEmployers": "SIGN-IN · MEMBERSHIP · EMPLOYERS",
  "obavijesti.pageTitle": "News",
  "obavijesti.all": "All news",
  "obavijesti.categories": "Categories",
  "obavijesti.search": "Search news…",
  "obavijesti.metaTitle": "News from Studentski centar Zagreb",
  "dorm.photos": "Photographs",
  "dorm.notFound": "Student hall not found",
  "empty.photos": "No photographs to show",

  "nutrition.importance": "Why good nutrition matters",
  "nutrition.varied": "A varied diet",
  "nutrition.vitamins": "Vitamins and minerals",
  "nutrition.activity": "Physical activity",
  "nutrition.weight": "A healthy body weight",
  "sign.title": "Digital signing",
  "sign.contracts": "Signing contracts digitally",
  "sign.extract": "Retrieve an employer contract from the Studentski centar Zagreb database of active employers.",
  "sign.mobile": "Sign contracts digitally on your phone using a level-4 security certificate. Fast, simple and secure.",
  "sign.sync": "Database synchronisation",
  "help.address": "ADDRESS",
  "help.email": "EMAIL ADDRESS",
  "help.phone": "TELEPHONE",
  "help.directorsOffice": "DIRECTOR'S OFFICE",
  "contract.number": "CONTRACT NUMBER",
  "contract.payments": "FEE PAYMENTS",
  "contract.taxFree": "TAX-FREE INCOME",
  "contract.signAfterEmployer": "SIGN AFTER THE EMPLOYER",
  "login.employer": "EMPLOYER",
  "login.student": "STUDENT",
  "login.employerSignIn": "EMPLOYER SIGN-IN",
  "login.studentSignIn": "STUDENT SIGN-IN",
  "nav.goHome": "Go to the home page",
  "nav.openMenu": "Open navigation",
  "ads.close": "Close advert",
  "rent.title": "Paying rent online",
  "rent.accessProfile": "Sign in to your personal profile at:",
  "rent.afterLogin": "Once signed in, click “",
  "rent.charges": "Naplata smještaja",
  "rent.selectWhat": "In the middle of the screen, select what you are paying for by ticking the empty checkbox.",
};

/** Resolve one key for a locale. Falls back to Croatian, never to the key. */
export const uiString = (locale: string | undefined, key: UIKey): string =>
  (isEnglish(locale) ? EN[key] : undefined) ?? HR[key];

/** Hook form, for components that already run on the client. */
export const useUI = () => {
  const { locale } = useRouter();
  return (key: UIKey) => uiString(locale, key);
};
